name: Generate a release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:

  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
            # user/app:latest
            # user/app:1.0.0                  
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.fouille.me
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            registry.fouille.me/${{ github.event.repository.name }}:latest 
            registry.fouille.me/${{ github.event.repository.name }}:${{ github.ref_name }}      

  create_release:
    runs-on: ubuntu-latest
    needs: build-container
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create Release
      uses: ncipollo/release-action@v1 #https://github.com/ncipollo/release-action
      with:
        # artifacts: "release.tar.gz,foo/*.txt"
        bodyFile: "src/README.md"
        draft: falseS
        prerelease: false
